### ISSUE TITLE
EU extension into the caucasus

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#996] opened 2017-03-23 21:27 UTC
well the title basically says it alreday. Have you considered to make Azerbaijan, Armenia and especially Georgia membership candidades for the EU? The EU themselves at least see them as potential members: https://upload.wikimedia.org/wikipedia/commons/f/f6/EU28-further_enlargement_map.svg It would definetely cause conflict with Russia and Turkey tho.

Additionally Israel might be a potentional member.

**Comment by simsulla** [comment] 2017-03-24 03:16
In part duplicate of Georgia can't join the EU #883
Armenia (eurasia), Azerbaijan(tc) are part of other "super-states". 

Israel joining EU I have no knowledge on any serious political force on any side, advocating this. Do you have a reference?

**Closed by simsulla** 2017-03-24 03:16 UTC
