### ISSUE TITLE
Cores & Nationalists 

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#298] opened 2016-04-02 21:54 UTC
There should be some way to gain cores without decisions, but under some very limeting circumstances, for example at least 30 % of your accepted/tolerated pop has to live there, increased militancy, etc.

Another thing are Nationalists. As I conquered Austria with Germany I had absolutly no Austrian Nationalists or Freedom Movements, same goes for Bavaria. Is this a bug or is it considered to work this way?

**Comment by simsulla** [comment] 2016-04-03 01:38
There are commands to detect if a pop is majority or any pops exists in a province, but no command to detect say 30%... So difficult to mod.
On Nationalists, agree, will investigate why this is not happening.

**Comment by Liegnitz** [comment] 2016-04-03 13:25
30 % was just an example, but I think coring would make sense.

**Comment by simsulla** [comment] 2016-04-04 02:16
I understand, but there are  no mod command to check for fraction of pop. Only pop_majority_culture or "any" of a particular culture in a selected set.

**Comment by Liegnitz** [comment] 2016-04-04 11:46
Hmm, I have seen an event concerning cores in PDM, which was about me (Italy) conquering France for Corsica, which has an Italian majority. 
After a while I got an event asking me to gain a core or not.

I don't know if it was coded to happen, or this event could apply to any nation.

**Comment by simsulla** [comment] 2016-04-05 03:17
I like the idea to gain core if your nation is a "principal-culture" nation. Will add it,

**Comment by simsulla** [comment] 2016-04-21 05:06
Bad news :(
Created event 11108 in political_national_unification.txt, but unable to get it to work. Comment;
`# this is dead code, as I can't get the "acting country". is_primary_culture = THIS, THIS is oddly enough "any_neighbor_country" not "THIS" countrys culture.`
The example you mention on Corsica is hard coded in PDM. 

The Nationalsits is a duplicate of #83.

**Closed** 2016-04-21 05:13 UTC

**Comment by simsulla** [comment] 2016-04-21 05:36
I am looking to get help with pretesting 1.06 (maybe Thursday 28/4, Friday 29/4 next week - leaving me Saturday to fix found issues). 1.06 release date is Saturday evening 30/4. Would you be interested in a doing a pretest game of 1.06 (I will provide a beta-download)? 
In 1.05 I accidentally put in bad code (colonial China) that should not have got throw release tests....

**Comment by Liegnitz** [comment] 2016-04-21 15:13
Well too bad that this coring doesn't work.

To the play testing, I'd love to do so, however I am on a trip exactly that week, so I have to pass. But I'm up for a 1.07 play test :smile:
