### ISSUE TITLE
Population Screen: Pop Changes Crash

### ISSUE THREAD

**Issue by James9883** [simsulla/nwomod#184] opened 2016-02-22 04:31 UTC
Whenever I hover over the circled area(or when I enter this screen), the game crashes. 
![](http://i.imgur.com/Dy39ZfQ.png)

**Comment by simsulla** [comment] 2016-02-22 05:07
Duplicate of CTD on hovering over POP migration #152

**Closed by simsulla** 2016-02-22 05:07 UTC
Labels: duplicate
