### ISSUE TITLE
Unhistorically early Soviet Dissolution

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#334] opened 2016-04-08 19:33 UTC
As Poland I got the 1989 elections event in about 1957/1958 which caused the soviet union to release the Baltic States, and Czechoslovakia, Hungary, Romania and Bulgaria to leave the bloc and Yugoslavia to break up, even thought I choose to keep the regime.

**Comment by simsulla** [comment] 2016-04-09 07:55
Duplicate of #264

**Closed by simsulla** 2016-04-09 07:55 UTC
