### ISSUE TITLE
Why does the communist bloc and Soviet union fall apart so early?

### ISSUE THREAD

**Issue by Madhate** [simsulla/nwomod#326] opened 2016-04-08 15:53 UTC
Every game I play the communist bloc seems to fall apart around the late 50s/early 60s, with the Soviets falling apart shortly after. Why so early?

**Comment by simsulla** [comment] 2016-04-08 16:42
This needs to be investigated. Do you have a save file just before the collapse?

**Comment by simsulla** [comment] 2016-04-09 09:03
Duplicate of #264

**Closed by simsulla** 2016-04-09 09:03 UTC
