### ISSUE TITLE
Incorrect political parties at 1946 start date

### ISSUE THREAD

**Issue by bvkscmskcsxd222** [simsulla/nwomod#1148] opened 2017-08-17 17:01 UTC
There are quite a few countries where their political parties at the 1946 start date do not match its historical counterparts.

Major problems:

Canada has a conservative party but it should be liberal
https://en.wikipedia.org/wiki/Canadian_federal_election,_1945

US has a liberal party but it should be democratic
https://en.wikipedia.org/wiki/United_States_presidential_election,_1944

Australia has a conservative party but it should be labour
https://en.wikipedia.org/wiki/Australian_federal_election,_1943

New Zealand has conservative party but it should be labour
https://en.wikipedia.org/wiki/New_Zealand_general_election,_1943

France has liberal party but it should be a coalition of socialist and communists
https://en.wikipedia.org/wiki/French_legislative_election,_1945

Italy's last election should have been in 1934 and not in 1945
https://en.wikipedia.org/wiki/Italian_general_election,_1934

Sweden has conservative party but should be socialist
https://en.wikipedia.org/wiki/Swedish_general_election,_1944

Switzerland has conservative party but should be socialist
https://en.wikipedia.org/wiki/Swiss_federal_election,_1943

Denmark has conservative party but should be socialist
https://en.wikipedia.org/wiki/Danish_Folketing_election,_1945

Mexico has conservative party but should be socialist
https://en.wikipedia.org/wiki/Mexican_general_election,_1940

Turkey has conservative party but should be socialist
https://en.wikipedia.org/wiki/Turkish_general_election,_1943

Also other countries where improvements could be made in their parliments:

Netherlands
https://en.wikipedia.org/wiki/Dutch_general_election,_1937

Belgium
https://en.wikipedia.org/wiki/Belgian_general_election,_1939

Luxemburg
https://en.wikipedia.org/wiki/Luxembourg_general_election,_1945

**Comment by simsulla** [comment] 2017-08-20 09:36
Closing - as duplicate of #1084

**Closed by simsulla** 2017-08-20 09:36 UTC
