### ISSUE TITLE
Issues and ideologies review

### ISSUE THREAD

**Issue by Grau87** [simsulla/nwomod#882] opened 2017-01-10 04:09 UTC
One of the things I've noticed is that, when Big Tent parties are in power, that it's impossible to promote party loyalty to them via national focus, since there is no national focus for Big Tent loyalty. In some cases, just using the Conservative option can have what I expect to be a similar effect, but in many countries (the USA for example), all the primary conservative parties are Big Tent in-game. Therefore, the national focus to promote Conservative is greyed out, as "there are no conservative parties currently active."

Would it even be possible to create a new focus for the new Big Tent type of party? If so, I'd love to see that, as it would make it much easier to support that type of party in a democracy, and prevent them from being voted out. A small issue, but one which could assist with specific political outcomes.

**Comment by simsulla** [comment] 2017-01-10 08:25
We will use this issue to take a more broad grip on ideologies. And as part of that address the Big Tent focus bug. 

The current system has several flaws - it fits the political scenario rather poorly in most cases. Even _little_ Sweden, which in part both the original Vic2 and NWO ideologies are modeled after, could be simplified. 

This is a tentative proposal for changes - that would be the basis for discussion. 

The basis of ideologies is political_reform(_whant) and social_reform(_whant). Their stance on social/political reform and how they respond to "whant". Militancy/revanschism gives room for ideologies outside the democratic spectrum (like communists). 

If one look on political election and more significantly parties in power - we see almost everywhere two parties or two agglomerates of parties struggling for power - depending on electoral system. Though it is not totally true in many cases (like Sweden, Brazil) still parties tend to agglomerate (like  the Lulistas in Brazil, the Alliance in Sweden) it is a good enough approximation, as long as we allow for an upset of the equilibrium be either outsiders (like communist) or by a shift in spectrum. 

So what should the political spectrum be? In vanilla Vic2 it is for or against social_reform or for or against social reform. This causes dynamic in the game by tension between socialist and liberals moving away from conservative - no/slow reform stance.
 
But in 1946 in (almost)no established party in power in a democracy is totally against all reforms (social and/or political). Instead a more dynamic approach is followed. Either tilting in the direction along a social-political reform axis or tilting along a slow-fast social_and_political reform axis. 
This graph illustrates the spectrum.
![image](https://cloud.githubusercontent.com/assets/10263809/21798660/fc0c8b3c-d715-11e6-8e9c-7d2281592694.png)

The US and modern Russian politics follow a slow-fast axis.
The UK and most European countries tilts towards a social-political reform axis.
Turkey and Turkey are countries that has shifted from a social-political to a slow-fast axis (APK and BJP).

**Comment by Grau87** [comment] 2017-01-11 06:27
Hmmm, interesting. I like the model, it's a good way of expressing how modern politics is more than "left and right". One thing though, regarding the US. I completely agree that the US follows the slow-fast axis from the 1992 start onwards, but before that it's a bit more complicated. The Democrats and Republicans both had 'conservative' and 'liberal' wings. According to your model, I'd estimate it as the Republicans having factions on both the right/blue sides, and the Democrats having factions on both the red/left. Starting in the 1960s, that changed, and by 1980 we ended up with the more-or-less modern system of Republicans (Big Tent) vs Democrats (Liberal). 

Let me know what your plans are for the political system. If you need help with research, I could do that. Besides that, excellent mod. V2 is one of my favorite games, and the modern era is badly neglected by strategy games. This is one of the best modern-day strategy scenarios I've encountered. Keep up the great work :)

**Comment by simsulla** [comment] 2017-01-12 04:52
Rename after merge with issue Issues and ideologies #822

**Comment by simsulla** [comment] 2017-03-15 19:14
**Dveduu**
What, so Brexit requires Britain to become a dictatorship? That seems a little unrealistic
**simsulla*
Populism has evolved in the mod - more caused by mod technical and practical conditions - than a design decision. It started out with the removal of vanilla Vic2 fascism, and then has been adopted to cover multiple movements (Franco in Spain, Vargas in Brazil, populist rise in Europe, Philippines, the US etc..). It is not a dictatorship. The government type is called "Republic", and has elections. So I agree "Republic" is not portrayed accurately and should be more democratic but less ideological, issue #882 covers this.

**Comment by simsulla** [comment] 2017-04-08 06:07
**River974**
Question: wh'at's the big tent outside USA ? If it's just for the usa are they realy a good idea to add them for all the country in the world ?[/QUOTE]
On the rebellion, that is a bug. Created issue #1055 No Nationalist Rebellions.

**simsulla**
On the Big Tent - yes at the moment only US. But a "big tent" political constallation is more common, will look into developing this.

**Comment by simsulla** [comment] 2017-04-11 18:39
**River974**
I made an add for two news national focus: https://mega.nz/#!B1BCEIoS!cOvLcm33fbxuO0QABIh7gQLxAJCG6jO3GLbWnifbnmk
Encourage cultural assimilation: +25%, 0.1 mil/month only valable with Limited Citizen
Encourage religion assimilation: +25%, 0.1 mil/month only valable with Moralism
I added new icons too.
[nwo_national_focus.zip](https://github.com/simsulla/nwomod/files/914345/nwo_national_focus.zip)

**Comment by simsulla** [comment] 2017-04-25 05:58
Some ideas thoughts on pop ideologies:
Looking in the poptypes files, pops have policies, issues(reforms).
A pop also they adhere to an ideology. Ideologies has a stance on reforms, and political parties (belonging to an ideology) has policies. The largest political party will form government in a democracy, and within an ideology the party with the most "policy, issue" pop support will be selected.  
There is a condition agree_with_ruling_party for issues.  If a pop get their life or luxury needs satisfied they will agree with the governing party policies, regardless what it is.  A similar setting could be used for ideologies, i.e. if a pop agree_with_ruling_party on policy it will adhere to that ideology. 
For the opposition ideologies(parties) they will attract their value from core pop properties (like type/class, religion, is_primary/accepted, revanchism and national_value).

The basic idea is that ideologists drive reform, **not** pops. Pops just want their needs satisfied, and will support a regime delivering this. Thus it is progressive/liberal/socialists party ideologues holding power that drives reform, not an inherent will of pops. 

Consciousness will make pops more "active", supporting opposition if not agree_with_ruling_party.

National value is important as it sets what political ideologies has prime in a nation (liberal/big_tent in the US, socialist/(Liberal)/Conservative in UK, Colombia, Sweden). And as national_value may change, the political setting can change (like Turkey going from Socialist/Conservative, to a Traditionalist/Big Tent, or US maybe in the future to a Progressive/Populist setup). National value should be changeable, as if a third ideology comes to power it will try and change the narrative.

**Comment by simsulla** [comment] 2017-04-29 05:33
New reform tree. The number of reforms are reduced, and those remaining are streamlined with regards to reform effects. LGBT reforms are merged with Gender Rights, which now has huge positive effect in terms of factory productivity (i.e. by work force participation of females). The "mobilization" effects previously part of LGBT now will be handled as part of events (#1026). Voting related reforms are merged into vote_franschise. The reform political_parties has changed as it now sets what cultures can vote. It does not necessary reflect actual laws in most cases but more factual composition of the political establishment. For example Iran, a theocracy, would have parties_only_nominated and registered_voting. So there are elections but favoring the ruling class. Regimes with elections but constrained (such as Assad's Syria and Apartheid SA) will have parties_only_nominated and registered_voting 
(leading to more ruling party support and voting being restirced to primary and accepted cultures). 
Similarly a liberal regime can strengthen its electoral position by setting parties_restrict_non_democratic. The erosion of democracy (to the benefit of the ruling party)  in many liberal democracies is implemented as a higher rich vote with the most liberal reform promoted_voting.

**Comment by simsulla** [comment] 2017-04-29 16:50
There will be some redesign of presidential_dictatorship and populist_dictatorship (Republic). Both will have elections. For a presidential_dictatorship every 8 year only allowing big tent 
and conservatives (ref Brazil junta in the 60s), thus pretty unfree. For a populist_dictatorship (Republic) there are elections but with very long interleave 50year (in reallity
no elections), but on leader succession (by event) an election is held (allowing conservative, big tent, populist and communist. These elections (populist and presidential) 
reflect the reconstitution of the regime. The result of the election sets the framework for reform of the regime.

**Comment by simsulla** [comment] 2017-04-30 05:43
Will tune the country specific element of the ideologies with help of national values when I do the nation play troughs.

**Closed** 2017-04-30 05:43 UTC
